---
AWSTemplateFormatVersion: "2010-09-09"
Description: OpenVPN server (Own VPC)

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "AWS Configuration"
        Parameters:
          - InstanceType
          - KeyName
          - HostedZoneName
      - Label:
          default: "OpenVPN Configuration"
        Parameters:
          - AdminUser
          - AdminPassword
          - RouteAllTraffic
          - UseVPNDNS

Parameters:
  InstanceType:
    Description: OpenVPN Instance Type
    Type: String
    AllowedValues:
      - t2.nano
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
      - t2.xlarge
      - t2.2xlarge
      # OpenVPN AMIs still don't support required ENA for T3s
      # - t3.nano
      # - t3.micro
      # - t3.small
      # - t3.medium
      # - t3.large
      # - t3.xlarge
      # - t3.2xlarge
    Default: t2.medium

  KeyName:
    Description: 'SSH Key Name'
    Type: AWS::EC2::KeyPair::KeyName

  HostedZoneName:
    Description: '[Optional] Create a record like "openvpn.eu-west-1." for your Hosted Zone'
    Type: String
    MinLength: 4
    MaxLength: 255

  AdminUser:
    Description: OpenVPN Admin User
    Type: String
    MinLength: 4
    MaxLength: 32
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: Must begin with a letter, be at least 4 chars long and only alphanumeric
    Default: openvpn

  AdminPassword:
    Description: OpenVPN Admin Password
    Type: String
    NoEcho: true
    MinLength: 8
    MaxLength: 32
    ConstraintDescription: Must be at least 8 chars long

  RouteAllTraffic:
    Description: Should all local traffic go over VPN when connected?
    Type: Number
    AllowedValues:
      - 0
      - 1
    Default: 1

  UseVPNDNS:
    Description: Should client use VPN supplied DNS when connected?
    Type: Number
    AllowedValues:
      - 0
      - 1
    Default: 1

Conditions:
  HasHostedZone: !Not [ !Equals [ !Ref HostedZoneName, "" ]]

Mappings:
  AWSRegionArch2AMI:
    # Software version 2.5.0 - 22/03/2018
    # N. Virginia
    us-east-1:
      HVM64: ami-1b9c4966
    # Ohio
    us-east-2:
      HVM64: ami-c9e8f725
    # N. California
    us-west-1:
      HVM64: ami-7b2e391b
    # Oregon
    us-west-2:
      HVM64: ami-ffd74b87
    # Canada
    ca-central-1:
      HVM64: ami-d4d650b0
    # Frankfurt
    eu-central-1:
      HVM64: ami-1c3767f7
    # Ireland
    eu-west-1:
      HVM64: ami-ebdc8992
    # London
    eu-west-2:
      HVM64: ami-cfc92fa8
    # Paris
    eu-west-3:
      HVM64: ami-b63583cb
    # Singapore
    ap-southeast-1:
      HVM64: ami-10277a6c
    # Sydney
    ap-southeast-2:
      HVM64: ami-96666ff5
    # Seoul
    ap-northeast-2:
      HVM64: ami-f52b879b
    # Tokyo
    ap-northeast-1:
      HVM64: ami-bf5203d9
    # Mumbai
    ap-south-1:
      HVM64: ami-c4f8a0ab
    # Sao Paulo
    sa-east-1:
      HVM64: ami-e036628c

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "10.0.0.0/16"
      Tags:
      - Key: Name
        Value: OpenVPN

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: "10.0.0.0/24"
      Tags:
      - Key: Name
        Value: OpenVPN Public Subnet

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC

  Route:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: "0.0.0.0/0"
      GatewayId: !Ref InternetGateway

  SubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref RouteTable

  IPAddress:
    Type: AWS::EC2::EIP
    Properties:
      Domain: "vpc"

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPC
      GroupDescription: Security group for OpenVPN Server
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp: "0.0.0.0/0"
      - IpProtocol: tcp
        FromPort: 943
        ToPort: 943
        CidrIp: "0.0.0.0/0"
      - IpProtocol: udp
        FromPort: 1194
        ToPort: 1194
        CidrIp: "0.0.0.0/0"

  OpenVPNInstance:
    Type: AWS::EC2::Instance
    DependsOn: IPAddress
    Properties:
      ImageId:
        Fn::FindInMap:
        - AWSRegionArch2AMI
        - Ref: AWS::Region
        - HVM64
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SecurityGroupIds:
      - !Ref SecurityGroup
      SubnetId: !Ref PublicSubnet
      Tags:
       - Key: Name
         Value: OpenVPN Instance
      UserData:
        Fn::Base64: !Sub |
          public_hostname=${IPAddress}
          admin_user=${AdminUser}
          admin_pw=${AdminPassword}
          reroute_gw=${RouteAllTraffic}
          reroute_dns=${UseVPNDNS}

  IPAssociaton:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId: !GetAtt IPAddress.AllocationId
      InstanceId: !Ref OpenVPNInstance

  DNSRecord:
    Type: AWS::Route53::RecordSet
    Condition: HasHostedZone
    Properties:
      HostedZoneName: !Ref 'HostedZoneName'
      Comment: Friendly DNS name for OpenVPN server
      Name: !Join ['', ['openvpn', ., !Ref 'AWS::Region', ., !Ref 'HostedZoneName']]
      Type: A
      TTL: '900'
      ResourceRecords:
      - !Ref IPAddress

Outputs:
  OpenVPNServerAdminURL:
    Description: OpenVPN Administration URL
    Value: !Sub https://${IPAddress}:943/admin
  OpenVPNServerURL:
    Description: OpenVPN Server URL
    Value: !Sub https://${IPAddress}
